# Generated by Django 3.2.6 on 2022-02-28 10:36

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220228_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='code2',
        ),
        migrations.AddField(
            model_name='account',
            name='public_key',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
